In [183]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import sklearn

In [184]:
#input data
data = 'C:/Users/User/Downloads/Jan_2019_ontime.csv' 
#menampilkan data
df = pd.read_csv(data)
df

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER  OP_CARRIER_AIRLINE_ID  \
0                  1            2                9E                  20363   
1                  1            2                9E                  20363   
2                  1            2                9E                  20363   
3                  1            2                9E                  20363   
4                  1            2                9E                  20363   
...              ...          ...               ...                    ...   
583980            31            4                UA                  19977   
583981            31            4                UA                  19977   
583982            31            4                UA                  19977   
583983            31            4                UA                  19977   
583984            31            4                UA                  19977   

       OP_CARRIER TAIL_NUM  OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID ORIGIN  \
0              9E   N8688C               3280              11953    GNV   
1              9E   N348PQ               3281              13487    MSP   
2              9E   N8896A               3282              11433    DTW   
3              9E   N8886A               3283              15249    TLH   
4              9E   N8974C               3284              10397    ATL   
...           ...      ...                ...                ...    ...   
583980         UA   N776UA                200              12016    GUM   
583981         UA   N36280                174              12016    GUM   
583982         UA   N36280                117              14955    SPN   
583983         UA   N39726                105              14955    SPN   
583984         UA   N39726                104              12016    GUM   

        DEST_AIRPORT_ID DEST  DEP_TIME  DEP_DEL15 DEP_TIME_BLK  ARR_TIME  \
0                 10397  ATL     601.0        0.0    0600-0659     722.0   
1                 11193  CVG    1359.0        0.0    1400-1459    1633.0   
2                 11193  CVG    1215.0        0.0    1200-1259    1329.0   
3                 10397  ATL    1521.0        0.0    1500-1559    1625.0   
4                 11778  FSM    1847.0        0.0    1900-1959    1940.0   
...                 ...  ...       ...        ...          ...       ...   
583980            12173  HNL     749.0        0.0    0700-0759    1832.0   
583981            14955  SPN     717.0        0.0    0700-0759     759.0   
583982            12016  GUM     857.0        0.0    0900-0959     933.0   
583983            12016  GUM    1820.0        0.0    1800-1859    1854.0   
583984            14955  SPN    1636.0        0.0    1600-1659    1719.0   

        ARR_DEL15  CANCELLED  DIVERTED  DISTANCE  
0             0.0          0         0       300  
1             0.0          0         0       596  
2             0.0          0         0       229  
3             0.0          0         0       223  
4             0.0          0         0       579  
...           ...        ...       ...       ...  
583980        0.0          0         0      3801  
583981        0.0          0         0       129  
583982        0.0          0         0       129  
583983        0.0          0         0       129  
583984        0.0          0         0       129  

[583985 rows x 19 columns]

In [185]:
#bentuk dimensi dataset (baris/kolom)
df.shape 

(583985, 19)

In [186]:
 #melihat kumpulan data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583985 entries, 0 to 583984
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   DAY_OF_MONTH           583985 non-null  int64  
 1   DAY_OF_WEEK            583985 non-null  int64  
 2   OP_UNIQUE_CARRIER      583985 non-null  object 
 3   OP_CARRIER_AIRLINE_ID  583985 non-null  int64  
 4   OP_CARRIER             583985 non-null  object 
 5   TAIL_NUM               581442 non-null  object 
 6   OP_CARRIER_FL_NUM      583985 non-null  int64  
 7   ORIGIN_AIRPORT_ID      583985 non-null  int64  
 8   ORIGIN                 583985 non-null  object 
 9   DEST_AIRPORT_ID        583985 non-null  int64  
 10  DEST                   583985 non-null  object 
 11  DEP_TIME               567633 non-null  float64
 12  DEP_DEL15              567630 non-null  float64
 13  DEP_TIME_BLK           583985 non-null  object 
 14  ARR_TIME               566924 non-nu

In [187]:
#mengetahui nilai yang kosong
df.isnull().sum() 

DAY_OF_MONTH                 0
DAY_OF_WEEK                  0
OP_UNIQUE_CARRIER            0
OP_CARRIER_AIRLINE_ID        0
OP_CARRIER                   0
TAIL_NUM                  2543
OP_CARRIER_FL_NUM            0
ORIGIN_AIRPORT_ID            0
ORIGIN                       0
DEST_AIRPORT_ID              0
DEST                         0
DEP_TIME                 16352
DEP_DEL15                16355
DEP_TIME_BLK                 0
ARR_TIME                 17061
ARR_DEL15                18022
CANCELLED                    0
DIVERTED                     0
DISTANCE                     0
dtype: int64

In [188]:
df.isnull().values.sum() #mengetahui data yang kosong

70333

In [189]:
#menghilangkan data yang tidak digunakan
dataframe = df.drop(columns=['DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 
'OP_CARRIER', 'TAIL_NUM', 'OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID', 'ORIGIN', 'DEST_AIRPORT_ID', 'DEST', 'DEP_TIME_BLK', 'DISTANCE', 'DIVERTED'])
#menampilkan data
dataframe = dataframe.head(100)

In [190]:
array = dataframe.values #mengubah dataframe menjadi array
X = array[:, :4] #slicing mundur 1 dari nomor tabel
Y = array[:,4]
print(X)

[[6.010e+02 0.000e+00 7.220e+02 0.000e+00]
 [1.359e+03 0.000e+00 1.633e+03 0.000e+00]
 [1.215e+03 0.000e+00 1.329e+03 0.000e+00]
 [1.521e+03 0.000e+00 1.625e+03 0.000e+00]
 [1.847e+03 0.000e+00 1.940e+03 0.000e+00]
 [8.530e+02 0.000e+00 9.530e+02 0.000e+00]
 [1.553e+03 0.000e+00 1.832e+03 0.000e+00]
 [1.551e+03 0.000e+00 1.824e+03 0.000e+00]
 [1.037e+03 0.000e+00 1.239e+03 0.000e+00]
 [1.245e+03 0.000e+00 1.318e+03 0.000e+00]
 [1.410e+03 0.000e+00 1.700e+03 0.000e+00]
 [5.570e+02 0.000e+00 7.370e+02 0.000e+00]
 [1.552e+03 0.000e+00 1.738e+03 1.000e+00]
 [2.029e+03 0.000e+00 2.259e+03 0.000e+00]
 [1.312e+03 0.000e+00 1.454e+03 0.000e+00]
 [1.450e+03 0.000e+00 1.637e+03 0.000e+00]
 [1.353e+03 1.000e+00 1.521e+03 1.000e+00]
 [1.148e+03 0.000e+00 1.236e+03 0.000e+00]
 [1.020e+03 0.000e+00 1.111e+03 0.000e+00]
 [8.170e+02 0.000e+00 9.320e+02 0.000e+00]
 [1.523e+03 0.000e+00 1.748e+03 0.000e+00]
 [1.111e+03 0.000e+00 1.157e+03 0.000e+00]
 [2.216e+03 0.000e+00 1.600e+01 1.000e+00]
 [1.554e+03

In [191]:
# memisahkan X dan Y menjadi data test dan data training

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [192]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [193]:
# import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB


# membuat fungsi klasifikasi naive bayes
gnb = GaussianNB()


# memasukkan data training pada fungsi klasifikasi naive bayes
gnb.fit(X_train, y_train)

GaussianNB()

In [194]:
# menentukan hasil prediksi  dari x_test
y_pred = gnb.predict(X_test)

y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [195]:
from sklearn.metrics import accuracy_score
#menampilkan nilai akurasi dari klasifikasi naive bayes
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score: 1.0000


In [196]:
# menentukan hasil prediksi  dari x_train
y_pred_train = gnb.predict(X_train)

y_pred_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [197]:
#menampilkan hasil akurasi 
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 1.0000


In [198]:
# menampilkan hasil data training dan data test

print('Training set score: {:.4f}'.format(gnb.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(gnb.score(X_test, y_test)))

Training set score: 1.0000
Test set score: 1.0000


In [199]:
# menampilkan confusion matriks dan dibagi menjadi 4 bagian

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

Confusion matrix

 [[20]]

True Positives(TP) =  20
